//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
